#line 2 "core/lexer/lex.yy.c"

#line 4 "core/lexer/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[320] =
    {   0,
        0,    0,  103,  101,   99,  100,   85,  101,   91,   84,
       79,   80,   89,   88,   76,   87,   83,   90,   43,   44,
       77,   73,   92,   78,   93,   96,   41,   81,   82,   94,
       41,   41,   41,   41,   41,   41,   40,   41,   41,   41,
       41,   41,   40,   41,   41,   41,   74,   95,   75,   86,
       99,   97,   99,   72,   98,   58,   75,   67,   59,   56,
       64,   54,   65,   55,   66,    0,   46,    1,    2,   57,
       47,   43,    0,    0,   43,   43,    0,   43,   44,   44,
       44,   44,   82,   74,   81,   63,   69,   71,   70,   62,
       41,   60,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   10,   41,   41,   41,   41,   41,   41,   41,   18,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   61,   68,   99,   97,   97,   51,    0,   46,
        2,   46,    0,   47,    0,   45,   43,   43,   43,   43,
        0,   42,   44,   44,   44,   44,   53,   52,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   16,   41,   41,   20,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    0,   46,    0,   46,    0,   47,
       45,   43,    0,    0,   42,    0,   42,   42,   44,   41,

       41,   41,    3,   41,    5,    6,   41,   41,   41,   41,
       12,   13,   41,   41,   41,   17,   41,   21,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   40,   41,   41,
       41,   34,   41,   41,    0,   46,    0,    0,    0,   42,
       42,    0,   48,   42,   42,   37,   41,   41,    4,    7,
       41,   41,   41,   41,   15,   41,   41,   41,   41,   25,
       41,   41,   41,   41,   41,   41,   32,   41,   41,   36,
        0,   49,    0,    0,   50,   48,   42,   41,   41,   41,
       41,   11,   14,   19,   41,   41,   24,   26,   27,   28,
       29,   30,   41,   41,   41,   49,    0,   49,   50,   41,

       41,   41,    9,   41,   41,   31,   41,   41,   49,   38,
       41,    8,   22,   23,   33,   35,   41,   39,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   25,   28,   29,
       30,   30,   31,   30,   30,   32,   30,   30,   30,   33,
       30,   30,   30,   30,   34,   30,   30,   35,   30,   30,
       36,    1,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   30,   49,   50,   51,   52,
       53,   54,   30,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    4,    4,    4,    1,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    5,
        5,    5,    6,    5,    5,    1,    1,    1,    5,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    6,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[325] =
    {   0,
        0,   66,  534,  535,  531,  535,  510,  526,   47,   65,
      535,  535,  508,   62,  535,   63,   61,   73,   82,   75,
      506,  535,   99,  506,   58,  535,    0,  535,  535,  505,
       75,  468,  470,   75,   60,   77,   84,  471,   45,  470,
      478,   88,   68,  469,  467,  472,  535,   86,  535,  535,
      137,  139,  516,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  503,  136,  535,    0,  535,
      143,  178,  183,  166,  115,   62,  502,  112,  191,  144,
      124,  179,  535,  535,  535,  493,  535,  535,  535,  492,
        0,  535,  460,  459,  460,  453,  465,  452,  467,  454,

      460,  446,  447,  444,  444,  450,  446,  443,  440,    0,
      100,  444,  158,  442,  157,  176,  446,  435,  438,   26,
      119,  443,  535,  535,  153,  488,  487,  535,  227,  535,
        0,  230,  239,  535,  173,  247,  184,  535,  456,  437,
        0,  237,  196,  535,  454,  435,  535,  535,  431,  432,
      442,  428,  440,  435,  423,  176,  437,  435,  431,  423,
      429,  416,  431,    0,  417,  421,    0,  422,  419,  409,
      407,  409,  411,  418,  404,  402,  402,  414,  413,  403,
      407,  411,  413,  402,  250,  267,  287,  535,  272,  290,
      535,  535,  206,  228,  279,  307,  277,  243,  535,  401,

      396,  403,    0,  399,    0,    0,  389,  390,  374,  381,
        0,    0,  375,  385,  370,    0,  374,    0,  369,  369,
      367,  364,  376,  366,  369,  374,  372,    0,  370,  359,
      364,    0,  352,  364,  298,  312,  332,  240,  342,  244,
      535,  315,  347,  375,  356,    0,  354,  348,    0,    0,
      332,  330,  334,  325,    0,  331,  304,  308,  302,    0,
      309,  306,  305,  289,  295,  295,    0,  286,  288,    0,
      350,  353,  370,  356,  373,  535,  535,  290,  274,  263,
      253,    0,    0,    0,  242,  239,    0,    0,    0,    0,
        0,    0,  227,  209,  184,  535,  377,  383,  535,  165,

      184,  177,    0,  162,  141,    0,  142,  122,  535,    0,
      108,    0,    0,    0,    0,    0,   69,    0,  535,  430,
      436,  440,  107,  441
    } ;

static const flex_int16_t yy_def[325] =
    {   0,
      319,    1,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  320,  319,  319,  319,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  321,  319,
      319,  319,  319,  319,  319,  319,  322,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      320,  319,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  319,  319,  319,  319,  319,  319,  319,  319,
      321,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      323,  322,  319,  319,  319,  319,  319,  319,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  319,  319,  319,  319,  319,  319,
      319,  319,  323,  324,  319,  319,  319,  319,  319,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  319,  319,  319,  324,  319,  319,
      319,  319,  319,  319,  319,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      319,  319,  319,  319,  319,  319,  319,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  319,  319,  319,  319,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  319,  320,
      320,  320,  320,  320,  320,  320,  320,  320,    0,  319,
      319,  319,  319,  319
    } ;

static const flex_int16_t yy_nxt[603] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   27,   39,   27,   40,
       27,   27,   27,   27,   41,   42,   43,   44,   45,   46,
       27,   27,   27,   47,   48,   49,   50,   51,   56,   57,
       52,   58,   61,  180,   66,   63,   67,   67,   67,   89,
       90,  181,   68,   62,   64,   65,   59,   69,   71,  110,
       79,   79,   79,  139,   70,   71,  111,   72,   72,   73,

       93,   94,   74,  101,   84,   95,   80,  123,   81,   74,
      193,  140,  102,   75,   98,   76,   77,   85,   74,   86,
       87,   99,  118,  106,   82,   74,  103,  100,  104,  119,
      318,   78,   81,  107,  114,  115,  108,  105,  125,   76,
      127,  126,   77,   55,  116,  138,  137,  117,  138,  166,
      124,   67,   67,   67,  125,  145,  167,  126,  132,  132,
      132,  137,  317,  129,  130,  316,  182,  130,  183,  138,
      133,  134,  138,  146,  134,  143,  135,  144,  135,  129,
      130,  136,  136,  136,  315,  130,  133,  134,  136,  136,
      136,   71,  134,   72,   72,   73,   71,  314,   73,   73,

       73,  144,  173,  169,   71,   74,   79,   79,   79,   75,
       74,   76,  144,  170,  171,  175,  313,  138,   74,  174,
      312,   74,   80,  311,   81,  310,   74,   78,  143,  144,
      176,  207,  208,  308,   74,   76,  144,  185,  237,  185,
       82,  138,  186,  186,  186,  132,  132,  132,   81,  189,
      194,  189,  307,  144,  190,  190,  190,  187,  188,  237,
      239,  188,  136,  136,  136,  186,  186,  186,  195,  196,
      197,  306,  273,  187,  188,  191,  241,  241,  191,  188,
      305,  239,  186,  186,  186,  304,  198,  190,  190,  190,
      196,  191,  240,  273,  197,  130,  191,  235,  130,  235,

      241,  241,  236,  236,  236,  190,  190,  190,  244,  303,
      240,  130,  241,  236,  236,  236,  130,  242,  134,  242,
      302,  134,  243,  243,  243,  301,  245,  236,  236,  236,
      243,  243,  243,  300,  134,  295,  241,  294,  293,  134,
      188,  292,  271,  188,  271,  291,  290,  272,  272,  272,
      289,  288,  274,  287,  274,  286,  188,  275,  275,  275,
      285,  188,  243,  243,  243,  272,  272,  272,  272,  272,
      272,  275,  275,  275,  284,  276,  283,  282,  276,  281,
      297,  296,  297,  280,  296,  298,  298,  298,  275,  275,
      275,  276,  298,  298,  298,  279,  276,  296,  298,  298,

      298,  299,  296,  278,  299,  277,  277,  270,  269,  268,
      267,  309,  266,  265,  309,  264,  263,  299,  262,  261,
      260,  259,  299,  258,  257,  256,  255,  309,  228,  254,
      253,  252,  309,   91,   91,   91,  131,  251,  131,  131,
      131,  131,  142,  142,  238,  250,  238,  249,  248,  247,
      246,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  206,  205,  204,
      203,  202,  201,  200,  199,  199,  192,  192,  127,  127,
      184,  179,  178,  177,  172,  168,  165,  164,  163,  162,

      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  141,  128,   53,  122,  121,
      120,  113,  112,  109,   97,   96,   92,   88,   83,   60,
       55,   54,   53,  319,    3,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319
    } ;

static const flex_int16_t yy_chk[603] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    9,    9,
        2,   10,   14,  120,   17,   16,   17,   17,   17,   25,
       25,  120,   18,   14,   16,   16,   10,   18,   20,   39,
       20,   20,   20,   76,   18,   19,   39,   19,   19,   19,

       31,   31,   20,   35,   23,   31,   20,   48,   20,   19,
      323,   76,   35,   19,   34,   19,   19,   23,   20,   23,
       23,   34,   43,   37,   20,   19,   36,   34,   36,   43,
      317,   19,   20,   37,   42,   42,   37,   36,   51,   19,
       52,   51,   19,   52,   42,   78,   75,   42,   75,  111,
       48,   67,   67,   67,  125,   81,  111,  125,   71,   71,
       71,   78,  311,   67,   67,  308,  121,   67,  121,   78,
       71,   71,   75,   81,   71,   80,   74,   80,   74,   67,
       67,   74,   74,   74,  307,   67,   71,   71,  135,  135,
      135,   72,   71,   72,   72,   72,   73,  305,   73,   73,

       73,   80,  115,  113,   79,   72,   79,   79,   79,   72,
       73,   72,   82,  113,  113,  116,  304,  137,   79,  115,
      302,   72,   79,  301,   79,  300,   73,   72,   82,  143,
      116,  156,  156,  295,   79,   72,   82,  129,  193,  129,
       79,  137,  129,  129,  129,  132,  132,  132,   79,  133,
      142,  133,  294,  143,  133,  133,  133,  132,  132,  193,
      194,  132,  136,  136,  136,  185,  185,  185,  142,  142,
      142,  293,  238,  132,  132,  136,  198,  240,  136,  132,
      286,  194,  186,  186,  186,  285,  142,  189,  189,  189,
      142,  136,  198,  238,  142,  186,  136,  187,  186,  187,

      198,  240,  187,  187,  187,  190,  190,  190,  197,  281,
      195,  186,  195,  235,  235,  235,  186,  196,  190,  196,
      280,  190,  196,  196,  196,  279,  197,  236,  236,  236,
      242,  242,  242,  278,  190,  269,  195,  268,  266,  190,
      236,  265,  237,  236,  237,  264,  263,  237,  237,  237,
      262,  261,  239,  259,  239,  258,  236,  239,  239,  239,
      257,  236,  243,  243,  243,  271,  271,  271,  272,  272,
      272,  274,  274,  274,  256,  243,  254,  253,  243,  252,
      273,  272,  273,  251,  272,  273,  273,  273,  275,  275,
      275,  243,  297,  297,  297,  248,  243,  272,  298,  298,

      298,  275,  272,  247,  275,  245,  244,  234,  233,  231,
      230,  298,  229,  227,  298,  226,  225,  275,  224,  223,
      222,  221,  275,  220,  219,  217,  215,  298,  214,  213,
      210,  209,  298,  320,  320,  320,  321,  208,  321,  321,
      321,  321,  322,  322,  324,  207,  324,  204,  202,  201,
      200,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  166,  165,
      163,  162,  161,  160,  159,  158,  157,  155,  154,  153,
      152,  151,  150,  149,  146,  145,  140,  139,  127,  126,
      122,  119,  118,  117,  114,  112,  109,  108,  107,  106,

      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   90,   86,   77,   66,   53,   46,   45,
       44,   41,   40,   38,   33,   32,   30,   24,   21,   13,
        8,    7,    5,    3,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[103] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "core/lexer/llexer.l"
/* Copyright Harsha Bhattacharyya 2025 */
/* This file is part of the C++Script project.

The C++Script project is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The C++Script project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with the C++Script project. If not, see <https://www.gnu.org/licenses/>. */
#line 12 "core/lexer/llexer.l"
/* 
 * This section contains C code that is copied directly into the generated
 * lexer source file. It's used for declarations, helper functions, and
 * including necessary headers.
 */

// The pparser.tab.h header is generated by Bison and contains the token definitions.
// It's included here to ensure the lexer and parser agree on token codes.
#include "../parser/pparser.tab.h"
#include <stdlib.h> // Required for malloc, strdup, etc.
#include <string.h> // Required for string manipulation functions like strdup.

/*
 * Note: This lexer is now configured for use with a Bison parser.
 * Token values are passed via the 'yylval' union. It is assumed that
 * the Bison grammar file defines a 'sval' field in the YYSTYPE union
 * for string-like values (e.g., %union { char *sval; }).
 * All constants and identifiers are passed as strings.
 *
 * MEMORY MANAGEMENT: This lexer uses strdup() to copy token text.
 * strdup() allocates memory that must be freed later to prevent memory leaks.
 * The Bison parser is responsible for freeing the memory for each token's sval
 * once it is no longer needed.
 */

// Global variables to track the position in the source file for error reporting.
int line_num = 1;
int col_num = 1;

// This function updates the column and line numbers based on the matched token text.
// It is called before returning a token to ensure the position is always current.
void count_position() {
    for (int i = 0; yytext[i] != '\0'; i++) {
        if (yytext[i] == '\n') {
            line_num++;
            col_num = 1;
        } else {
            col_num++;
        }
    }
}

#line 767 "core/lexer/lex.yy.c"
/* 
 * Flex options to configure the generated scanner.
 * noyywrap: Makes the scanner stop when it reaches the end of the file,
 *           rather than looking for a yywrap() function to open another file.
 * yylineno: Tells Flex to automatically track the current line number in the
 *           global variable 'yylineno'. While we use a custom 'line_num',
 *           this can be useful for debugging.
 */
/* 
 * Regular expression definitions. These are shorthand names for common
 * patterns, making the main rules section cleaner and more readable.
 */
/* D for a single digit */
/* L for a letter or underscore, the start of an identifier */
/* H for a hexadecimal digit */
/* E for scientific notation exponent */
/* P for hexadecimal floating-point exponent */
/* FS for a floating-point suffix (f, F, l, L) */
/* IS for an integer suffix (u, l, ll, combinations) */
/* Whitespace characters to be ignored by the lexer. */
#line 788 "core/lexer/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 89 "core/lexer/llexer.l"

#line 1010 "core/lexer/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 535 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "core/lexer/llexer.l"
{
                  int c;
                  while ((c = input()) != 0) {
                      if (c == '\n') {
                          line_num++;
                          col_num = 1;
                      } else {
                          col_num++;
                      }
                      if (c == '*') {
                          if ((c = input()) == '/') {
                              col_num++;
                              break;
                          } else {
                              unput(c);
                          }
                      }
                  }
                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 "core/lexer/llexer.l"
{ /* C++-style comment, ignored */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 110 "core/lexer/llexer.l"
{ count_position(); return AUTO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 111 "core/lexer/llexer.l"
{ count_position(); return BREAK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 112 "core/lexer/llexer.l"
{ count_position(); return CASE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 113 "core/lexer/llexer.l"
{ count_position(); return CHAR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 114 "core/lexer/llexer.l"
{ count_position(); return CONST; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 115 "core/lexer/llexer.l"
{ count_position(); return CONTINUE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 116 "core/lexer/llexer.l"
{ count_position(); return DEFAULT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "core/lexer/llexer.l"
{ count_position(); return DO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 118 "core/lexer/llexer.l"
{ count_position(); return DOUBLE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 119 "core/lexer/llexer.l"
{ count_position(); return ELSE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 120 "core/lexer/llexer.l"
{ count_position(); return ENUM; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 121 "core/lexer/llexer.l"
{ count_position(); return EXTERN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "core/lexer/llexer.l"
{ count_position(); return FLOAT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "core/lexer/llexer.l"
{ count_position(); return FOR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "core/lexer/llexer.l"
{ count_position(); return GOTO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "core/lexer/llexer.l"
{ count_position(); return IF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "core/lexer/llexer.l"
{ count_position(); return INLINE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 "core/lexer/llexer.l"
{ count_position(); return INT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "core/lexer/llexer.l"
{ count_position(); return LONG; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 129 "core/lexer/llexer.l"
{ count_position(); return REGISTER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 130 "core/lexer/llexer.l"
{ count_position(); return RESTRICT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 131 "core/lexer/llexer.l"
{ count_position(); return RETURN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 132 "core/lexer/llexer.l"
{ count_position(); return SHORT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 133 "core/lexer/llexer.l"
{ count_position(); return SIGNED; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 134 "core/lexer/llexer.l"
{ count_position(); return SIZEOF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 135 "core/lexer/llexer.l"
{ count_position(); return STATIC; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "core/lexer/llexer.l"
{ count_position(); return STRUCT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "core/lexer/llexer.l"
{ count_position(); return SWITCH; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 138 "core/lexer/llexer.l"
{ count_position(); return TYPEDEF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 139 "core/lexer/llexer.l"
{ count_position(); return UNION; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "core/lexer/llexer.l"
{ count_position(); return UNSIGNED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "core/lexer/llexer.l"
{ count_position(); return VOID; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "core/lexer/llexer.l"
{ count_position(); return VOLATILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 143 "core/lexer/llexer.l"
{ count_position(); return WHILE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 144 "core/lexer/llexer.l"
{ count_position(); return _BOOL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 145 "core/lexer/llexer.l"
{ count_position(); return _COMPLEX; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "core/lexer/llexer.l"
{ count_position(); return _IMAGINARY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 147 "core/lexer/llexer.l"
{ count_position(); return BOOL_LITERAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 148 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 149 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return INTEGER_CONSTANT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 150 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return INTEGER_CONSTANT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 151 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return INTEGER_CONSTANT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 153 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 154 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 157 "core/lexer/llexer.l"
{ count_position(); yylval.sval = strdup(yytext); return FLOATING_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 159 "core/lexer/llexer.l"
{ count_position(); return ELLIPSIS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 160 "core/lexer/llexer.l"
{ count_position(); return RIGHT_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 161 "core/lexer/llexer.l"
{ count_position(); return LEFT_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 162 "core/lexer/llexer.l"
{ count_position(); return ADD_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 163 "core/lexer/llexer.l"
{ count_position(); return SUB_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 164 "core/lexer/llexer.l"
{ count_position(); return MUL_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 165 "core/lexer/llexer.l"
{ count_position(); return DIV_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 166 "core/lexer/llexer.l"
{ count_position(); return MOD_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 167 "core/lexer/llexer.l"
{ count_position(); return AND_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 168 "core/lexer/llexer.l"
{ count_position(); return XOR_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 169 "core/lexer/llexer.l"
{ count_position(); return OR_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 170 "core/lexer/llexer.l"
{ count_position(); return RIGHT_SHIFT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 171 "core/lexer/llexer.l"
{ count_position(); return LEFT_SHIFT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 172 "core/lexer/llexer.l"
{ count_position(); return INC_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "core/lexer/llexer.l"
{ count_position(); return DEC_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 174 "core/lexer/llexer.l"
{ count_position(); return ARROW; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 175 "core/lexer/llexer.l"
{ count_position(); return AND_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 176 "core/lexer/llexer.l"
{ count_position(); return OR_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 177 "core/lexer/llexer.l"
{ count_position(); return LE_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 178 "core/lexer/llexer.l"
{ count_position(); return GE_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 179 "core/lexer/llexer.l"
{ count_position(); return EQ_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 180 "core/lexer/llexer.l"
{ count_position(); return NE_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 181 "core/lexer/llexer.l"
{ count_position(); return ';'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 182 "core/lexer/llexer.l"
{ count_position(); return '{'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 183 "core/lexer/llexer.l"
{ count_position(); return '}'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 184 "core/lexer/llexer.l"
{ count_position(); return ','; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 185 "core/lexer/llexer.l"
{ count_position(); return ':'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 186 "core/lexer/llexer.l"
{ count_position(); return '='; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 187 "core/lexer/llexer.l"
{ count_position(); return '('; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 188 "core/lexer/llexer.l"
{ count_position(); return ')'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "core/lexer/llexer.l"
{ count_position(); return '['; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 190 "core/lexer/llexer.l"
{ count_position(); return ']'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "core/lexer/llexer.l"
{ count_position(); return '.'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 192 "core/lexer/llexer.l"
{ count_position(); return '&'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "core/lexer/llexer.l"
{ count_position(); return '!'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "core/lexer/llexer.l"
{ count_position(); return '~'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "core/lexer/llexer.l"
{ count_position(); return '-'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 196 "core/lexer/llexer.l"
{ count_position(); return '+'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 197 "core/lexer/llexer.l"
{ count_position(); return '*'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 198 "core/lexer/llexer.l"
{ count_position(); return '/'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 199 "core/lexer/llexer.l"
{ count_position(); return '%'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 200 "core/lexer/llexer.l"
{ count_position(); return '<'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 201 "core/lexer/llexer.l"
{ count_position(); return '>'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 202 "core/lexer/llexer.l"
{ count_position(); return '^'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 203 "core/lexer/llexer.l"
{ count_position(); return '|'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 204 "core/lexer/llexer.l"
{ count_position(); return '?'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 205 "core/lexer/llexer.l"
{ count_position(); return HASH; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 206 "core/lexer/llexer.l"
{ count_position(); return DOUBLE_HASH; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 207 "core/lexer/llexer.l"
{ count_position(); }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 208 "core/lexer/llexer.l"
{ line_num++; col_num = 1; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 209 "core/lexer/llexer.l"
{ count_position(); fprintf(stderr, "Line %d, Col %d: Unknown character '%s'\n", line_num, col_num, yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 210 "core/lexer/llexer.l"
ECHO;
	YY_BREAK
#line 1607 "core/lexer/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 319);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 210 "core/lexer/llexer.l"


